#!/usr/bin/env bash
# configures a new Ubuntu machine for nginx

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default

sudo service nginx restart
