#!/bin/env bash
# script that displays the content of the file /etc/passwd
while IFS=: read -r username _ user_id _ _ home_directory _
do
  echo "$username:$user_id:$home_directory"
done < /etc/passwd
