#!/usr/bin/env bash
# changes ip addresses fro some sites
cp /etc/hosts ~/hosts.new
# Check if "localhost" is present in any line and replace the first occurrence
if grep -q "127.0.0.1	localhost" ~/hosts.new; then
  sed -i '0,/localhost/s/127.0.0.1/127.0.0.2/' ~/hosts.new
else
  echo "127.0.0.2  localhost" >> ~/hosts.new
fi
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
